coverage:
  precision: 2
  round: nearest
  #range - below minimum range, coverage badge (we'll get to badges in a sec) will be red, and as approching to 100% it will become greener
  range: "40...70"
  #ignore tag- all files which are not "meant" to be unit-tested, like GUI and constants-files
  # so coverage percent won't be reduce by this code.
  ignore:
  - "zerocode/src/main/java/org/jsmart/zerocode/converter/SoapMocker.java"
  - "zerocode/src/main/java/org/jsmart/zerocode/core/domain/builders/HighChartColumnHtmlBuilder.java"
  - "zerocode/src/main/java/org/jsmart/zerocode/core/domain/Assertions.java"
  - "zerocode/src/main/java/org/jsmart/zerocode/core/domain/Body.java"
  - "zerocode/src/main/java/org/jsmart/zerocode/core/domain/QueryParams.java"
  - "zerocode/src/main/java/org/jsmart/zerocode/core/domain/Request.java"
  - "zerocode/src/main/java/org/jsmart/zerocode/core/verify/SmartJUnitNavigatorVerification.java"
  - "zerocode/src/main/java/org/jsmart/zerocode/core/verify/SmartPackagedVerification.java"
  - "zerocode/src/main/java/org/jsmart/zerocode/core/zzignored/env/EnvVarReader.java"
  - "zerocode/src/main/java/org/jsmart/zerocode/core/zzignored/mocking/WireMockJsonContentTesting.java"
  - "zerocode/src/main/java/org/jsmart/zerocode/core/zzignored/trick/JacksonCsv.java"
  - "zerocode/src/main/java/org/jsmart/zerocode/core/zzignored/trick/JSON2CSV.java"
  - "zerocode/src/main/java/org/jsmart/zerocode/core/zzignored/trick/LogHello.java"
  - "zerocode/src/main/java/org/jsmart/zerocode/core/zzignored/trick/NotifierFuncMain.java"
  - "zerocode/src/main/java/org/jsmart/zerocode/core/zzignored/ZeroCodeException.java"
  - "zerocode/src/main/java/org/jsmart/zerocode/core/AddService.java"
  - "zerocode/src/main/java/org/jsmart/zerocode/core/httpclient/ssl/CorporateProxyNoSslContextHttpClient.java"
  - "zerocode/src/main/java/org/jsmart/zerocode/core/httpclient/ssl/SslTrustCorporateProxyHttpClient.java"
  - "zerocode/src/main/java/org/jsmart/zerocode/core/httpclient/ssl/SslTrustHttpClient.java"
